# Generated by Django 5.2.17 on 2026-09-15 06:58

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_locales'),
        ('media_library', '0003_video'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotline_phone', models.CharField(blank=True, help_text='Format: +998 XX XXX-XX-XX', max_length=32, verbose_name='hotline phone')),
                ('hotline_phone_secondary', models.CharField(blank=True, max_length=32, verbose_name='second hotline phone')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram channel')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok')),
                ('footer_text_uz', models.TextField(blank=True, verbose_name='footer text (uz)')),
                ('footer_text_ru', models.TextField(blank=True, verbose_name='footer text (ru)')),
                ('disclaimer_uz', models.TextField(default='Sayt tashxis qoʻymaydi; shifokorga murojaat qiling. [[TODO: content — copywriter]]', verbose_name='medical disclaimer (uz)')),
                ('disclaimer_ru', models.TextField(default='Сайт не ставит диагноз; обратитесь к врачу. [[TODO: content — copywriter]]', verbose_name='medical disclaimer (ru)')),
                ('emergency_banner_enabled', models.BooleanField(default=False, verbose_name='show emergency banner')),
                ('emergency_banner_uz', models.CharField(blank=True, max_length=300, verbose_name='emergency banner (uz)')),
                ('emergency_banner_ru', models.CharField(blank=True, max_length=300, verbose_name='emergency banner (ru)')),
                ('emergency_banner_link', models.URLField(blank=True, verbose_name='emergency banner link')),
                ('metrika_id', models.CharField(blank=True, max_length=32, verbose_name='Yandex.Metrika counter id')),
                ('legal_text_uz', wagtail.fields.RichTextField(blank=True, verbose_name='legal / privacy text (uz)')),
                ('legal_text_ru', wagtail.fields.RichTextField(blank=True, verbose_name='legal / privacy text (ru)')),
                ('partner_agency_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.portalimage', verbose_name='Agency logo')),
                ('partner_hamroh_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.portalimage', verbose_name='Hamroh logo')),
                ('partner_yandex_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.portalimage', verbose_name='Yandex logo')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'site settings',
            },
        ),
    ]
