# Generated by Django 5.2.17 on 2026-09-15 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_page',
            field=models.ForeignKey(blank=True, help_text='Linked from the consent banner and every form.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='privacy policy page'),
        ),
    ]
