# Generated by Django 5.2.17 on 2026-09-24 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_story_image_and_privacy'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_page',
            field=models.ForeignKey(blank=True, help_text='Header menu item «Haqimizda» — its translation per language.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='«About us» page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='doctors_page',
            field=models.ForeignKey(blank=True, help_text='Header menu item «Shifokorlar» — its translation per language.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='«Doctors» page'),
        ),
    ]
