# Generated by Django 5.2.17 on 2026-10-06 11:17

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_header_menu_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_columns_ru',
            field=wagtail.fields.StreamField([('column', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Column title', 'max_length': 80}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Label', 'max_length': 120}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional, without # — e.g. a section of a long page.', 'label': 'Anchor on the page', 'max_length': 80, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'or external URL', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('label', 1), ('page', 2), ('anchor', 3), ('url', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Links'}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 6)]], {})}, help_text='The footer site map (design 2026-10): one block per column, links in order.', verbose_name='footer columns (ru)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_columns_uz',
            field=wagtail.fields.StreamField([('column', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Column title', 'max_length': 80}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Label', 'max_length': 120}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional, without # — e.g. a section of a long page.', 'label': 'Anchor on the page', 'max_length': 80, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'or external URL', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('label', 1), ('page', 2), ('anchor', 3), ('url', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Links'}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 6)]], {})}, help_text='The footer site map (design 2026-10): one block per column, links in order.', verbose_name='footer columns (uz)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_url',
            field=models.URLField(blank=True, help_text='Footer location icon (e.g. Yandex Maps).', verbose_name='location on the map'),
        ),
    ]
