# Generated by Django 5.2.17 on 2026-10-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_footer_columns_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='address (ru)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_uz',
            field=models.CharField(blank=True, help_text='Footer location icon; opens Yandex Maps when no map link is set.', max_length=300, verbose_name='address (uz)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hotline_phone',
            field=models.CharField(blank=True, help_text='Format: +998 XX XXX-XX-XX or a short number such as 1303', max_length=32, verbose_name='hotline phone'),
        ),
    ]
