# Generated by Django 5.2.17 on 2026-10-08 06:55

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cta_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='directions',
            field=wagtail.fields.StreamField([('card', 10)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('breast', 'Breast cancer'), ('cervical', 'Cervical cancer'), ('children', 'Childhood cancer')], 'label': 'Topic (card colour)'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 80}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Short description', 'max_length': 240, 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page opened by the arrow', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Label', 'max_length': 120}), 5: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional, without # — e.g. a section of a long page.', 'label': 'Anchor on the page', 'max_length': 80, 'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'label': 'or external URL', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('label', 4), ('page', 5), ('anchor', 6), ('url', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'label': 'Links', 'max_num': 4}), 10: ('wagtail.blocks.StructBlock', [[('topic', 0), ('title', 1), ('text', 2), ('page', 3), ('links', 9)]], {})}, verbose_name='direction cards'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='directions_eyebrow',
            field=models.CharField(blank=True, max_length=80, verbose_name='eyebrow'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='directions_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='text on the right'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='directions_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_eyebrow',
            field=models.CharField(blank=True, help_text="Small line above the title (empty = the design's wording).", max_length=120, verbose_name='hero eyebrow'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='screening_eyebrow',
            field=models.CharField(blank=True, max_length=80, verbose_name='eyebrow'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='screening_steps',
            field=wagtail.fields.StreamField([('step', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 80}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Text', 'max_length': 240, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Link label', 'max_length': 60, 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Link page', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Without #.', 'label': 'Anchor on the page', 'max_length': 80, 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'label': 'or external URL', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1), ('link_label', 2), ('page', 3), ('anchor', 4), ('url', 5)]], {})}, verbose_name='steps'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='screening_text',
            field=models.TextField(blank=True, max_length=500, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='screening_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='title'),
        ),
    ]
