# Generated by Django 5.2.17 on 2026-09-15 09:54

import apps.core.fields
import django.db.models.deletion
import wagtail.fields
import wagtail.search.index
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0003_video'),
        ('wagtailcore', '0094_alter_page_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_image_generated', models.ImageField(blank=True, editable=False, help_text='Rendered automatically on publish when no sharing image is chosen.', upload_to='og/', verbose_name='generated sharing image')),
                ('noindex', models.BooleanField(default=False, help_text='Adds a noindex meta tag. Use for drafts-in-public and utility pages.', verbose_name='hide from search engines')),
                ('last_reviewed_at', models.DateField(blank=True, null=True, verbose_name='reviewed on')),
                ('medically_verified', models.BooleanField(default=False, help_text="Shows the 'Verified by a doctor' badge. Set by the medical reviewer.", verbose_name='medically verified')),
                ('intro', wagtail.fields.StreamField([('rich_text', 0), ('callout', 4), ('cards_grid', 15), ('stat', 20), ('cta', 25), ('video', 30)], blank=True, block_lookup={0: ('apps.articles.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link', 'document-link', 'image', 'embed']}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger — do not delay'), ('success', 'Success / good news'), ('reassurance', 'Reassurance (this sign is not always cancer)')], 'label': 'Kind'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 120, 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link'], 'label': 'Text'}), 4: ('wagtail.blocks.StructBlock', [[('kind', 1), ('title', 2), ('text', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Heading', 'max_length': 160, 'required': False}), 6: ('wagtail.images.blocks.ImageBlock', [], {'label': 'Image'}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional icon identifier for the designer (e.g. 'dna', 'age').", 'label': 'Icon name', 'max_length': 40, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 160}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link'], 'label': 'Text', 'required': False}), 10: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page', 'required': False}), 11: ('wagtail.blocks.URLBlock', (), {'label': 'External URL', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('page', 10), ('url', 11)]], {'label': 'Link', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('image', 6), ('icon', 7), ('title', 8), ('text', 9), ('link', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'label': 'Cards', 'min_num': 1}), 15: ('wagtail.blocks.StructBlock', [[('title', 5), ('cards', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': "E.g. '1 из 8' or '45–65'.", 'label': 'Value', 'max_length': 40}), 17: ('wagtail.blocks.CharBlock', (), {'label': 'Label', 'max_length': 200}), 18: ('wagtail.blocks.CharBlock', (), {'label': 'Source', 'max_length': 200, 'required': False}), 19: ('wagtail.blocks.IntegerBlock', (), {'label': 'Year', 'max_value': 2100, 'min_value': 1990, 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('value', 16), ('label', 17), ('source', 18), ('year', 19)]], {}), 21: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Text', 'required': False}), 22: ('wagtail.blocks.CharBlock', (), {'label': 'Button label', 'max_length': 80}), 23: ('wagtail.blocks.StructBlock', [[('page', 10), ('url', 11)]], {'label': 'Link'}), 24: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary (section colour)'), ('secondary', 'Secondary')], 'label': 'Style'}), 25: ('wagtail.blocks.StructBlock', [[('text', 21), ('button_label', 22), ('link', 23), ('style', 24)]], {}), 26: ('wagtail.snippets.blocks.SnippetChooserBlock', ('media_library.Video',), {'label': 'Video from library', 'required': False}), 27: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube, Telegram, Instagram or TikTok link (used when no library video).', 'label': 'External URL', 'required': False}), 28: ('wagtail.blocks.CharBlock', (), {'label': 'Caption', 'max_length': 300, 'required': False}), 29: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link'], 'label': 'Transcript', 'required': False}), 30: ('wagtail.blocks.StructBlock', [[('video', 26), ('external_url', 27), ('caption', 28), ('transcript', 29)]], {})}, verbose_name='intro')),
                ('form_intro', wagtail.fields.RichTextField(blank=True, verbose_name='text above the form')),
                ('thanks_text', wagtail.fields.RichTextField(default='<p>[[TODO: content — copywriter]]</p>', verbose_name='thank-you text')),
                ('last_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='medically reviewed by')),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when the page is shared in Telegram/Facebook. Generated automatically if empty.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.portalimage', verbose_name='social sharing image')),
            ],
            options={
                'verbose_name': 'questions & answers page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='name (optional)')),
                ('contact', apps.core.fields.EncryptedCharField(blank=True, help_text='Phone or e-mail. Encrypted at rest, deleted 90 days after the answer.', max_length=200, verbose_name='contact (optional, encrypted)')),
                ('section', models.CharField(choices=[('women', "Women's cancer"), ('children', 'Childhood cancer'), ('other', 'Other')], db_index=True, max_length=16, verbose_name='section')),
                ('text', models.TextField(max_length=2000, verbose_name='question')),
                ('consent_to_publish', models.BooleanField(default=False, verbose_name='may be published anonymously')),
                ('language', models.CharField(default='uz', max_length=8, verbose_name='language')),
                ('status', models.CharField(choices=[('new', 'New'), ('answered', 'Answered (private)'), ('published', 'Published'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=16, verbose_name='status')),
                ('public_question', models.TextField(blank=True, help_text='Edited/anonymised wording shown on the site (empty = original text).', verbose_name='question as published')),
                ('answer', wagtail.fields.RichTextField(blank=True, verbose_name='answer')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='answered at')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('contact_purged_at', models.DateTimeField(blank=True, null=True, verbose_name='contact purged at')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='answered by')),
            ],
            options={
                'verbose_name': 'question to a doctor',
                'verbose_name_plural': 'questions to a doctor',
                'ordering': ['-created_at'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
