# Generated by Django 5.2.17 on 2026-10-06 11:45

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_alter_faqpage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqpage',
            name='info_cards',
            field=wagtail.fields.StreamField([('card', 5)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('', 'All topics'), ('breast', 'Breast cancer'), ('cervical', 'Cervical cancer'), ('children', 'Childhood cancer')], 'label': 'Topic', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 80}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Without #.', 'label': 'Anchor on the page', 'max_length': 80, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'or external URL', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('topic', 0), ('title', 1), ('page', 2), ('anchor', 3), ('url', 4)]], {})}, help_text='Short links to pages, shown next to the most asked questions.', verbose_name='«Information you should know» cards'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Shown as a card under «Most asked questions» (published questions only).', verbose_name='most asked'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, choices=[('breast', 'Breast cancer'), ('cervical', 'Cervical cancer'), ('children', 'Childhood cancer')], db_index=True, help_text='Which disease page shows the published question.', max_length=16, verbose_name='topic'),
        ),
    ]
