# Generated by Django 5.2.17 on 2026-10-08 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0006_alter_faqpage_intro'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='article',
            field=models.ForeignKey(blank=True, help_text='Optional «Full article» link under the answer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='full article'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, choices=[('general', 'General information'), ('signs', 'Signs and causes'), ('screening', 'Screening'), ('treatment', 'Treatment')], db_index=True, help_text='Groups published questions in the side list of the question page.', max_length=16, verbose_name='category'),
        ),
    ]
