# Generated by Django 5.2.17 on 2026-09-15 06:58

import django.core.validators
import django.db.models.deletion
import wagtail.fields
import wagtail.search.index
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0003_video'),
        ('wagtailcore', '0094_alter_page_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=16, unique=True, verbose_name='code')),
                ('name_uz', models.CharField(max_length=100, verbose_name='name (uz)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='name (ru)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'regions',
                'ordering': ['sort_order', 'name_uz'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='code')),
                ('name_uz', models.CharField(max_length=120, verbose_name='name (uz)')),
                ('name_ru', models.CharField(max_length=120, verbose_name='name (ru)')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['name_uz'],
            },
        ),
        migrations.CreateModel(
            name='DirectoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('noindex', models.BooleanField(default=False, help_text='Adds a noindex meta tag. Use for drafts-in-public and utility pages.', verbose_name='hide from search engines')),
                ('last_reviewed_at', models.DateField(blank=True, null=True, verbose_name='reviewed on')),
                ('medically_verified', models.BooleanField(default=False, help_text="Shows the 'Verified by a doctor' badge. Set by the medical reviewer.", verbose_name='medically verified')),
                ('intro', wagtail.fields.StreamField([('rich_text', 0), ('callout', 4), ('cards_grid', 15), ('stat', 20), ('cta', 25), ('video', 30)], blank=True, block_lookup={0: ('apps.articles.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link', 'document-link', 'image', 'embed']}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger — do not delay'), ('success', 'Success / good news'), ('reassurance', 'Reassurance (this sign is not always cancer)')], 'label': 'Kind'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 120, 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link'], 'label': 'Text'}), 4: ('wagtail.blocks.StructBlock', [[('kind', 1), ('title', 2), ('text', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Heading', 'max_length': 160, 'required': False}), 6: ('wagtail.images.blocks.ImageBlock', [], {'label': 'Image'}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional icon identifier for the designer (e.g. 'dna', 'age').", 'label': 'Icon name', 'max_length': 40, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 160}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link'], 'label': 'Text', 'required': False}), 10: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page', 'required': False}), 11: ('wagtail.blocks.URLBlock', (), {'label': 'External URL', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('page', 10), ('url', 11)]], {'label': 'Link', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('image', 6), ('icon', 7), ('title', 8), ('text', 9), ('link', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'label': 'Cards', 'min_num': 1}), 15: ('wagtail.blocks.StructBlock', [[('title', 5), ('cards', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': "E.g. '1 из 8' or '45–65'.", 'label': 'Value', 'max_length': 40}), 17: ('wagtail.blocks.CharBlock', (), {'label': 'Label', 'max_length': 200}), 18: ('wagtail.blocks.CharBlock', (), {'label': 'Source', 'max_length': 200, 'required': False}), 19: ('wagtail.blocks.IntegerBlock', (), {'label': 'Year', 'max_value': 2100, 'min_value': 1990, 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('value', 16), ('label', 17), ('source', 18), ('year', 19)]], {}), 21: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Text', 'required': False}), 22: ('wagtail.blocks.CharBlock', (), {'label': 'Button label', 'max_length': 80}), 23: ('wagtail.blocks.StructBlock', [[('page', 10), ('url', 11)]], {'label': 'Link'}), 24: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary (section colour)'), ('secondary', 'Secondary')], 'label': 'Style'}), 25: ('wagtail.blocks.StructBlock', [[('text', 21), ('button_label', 22), ('link', 23), ('style', 24)]], {}), 26: ('wagtail.snippets.blocks.SnippetChooserBlock', ('media_library.Video',), {'label': 'Video from library', 'required': False}), 27: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube, Telegram, Instagram or TikTok link (used when no library video).', 'label': 'External URL', 'required': False}), 28: ('wagtail.blocks.CharBlock', (), {'label': 'Caption', 'max_length': 300, 'required': False}), 29: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link'], 'label': 'Transcript', 'required': False}), 30: ('wagtail.blocks.StructBlock', [[('video', 26), ('external_url', 27), ('caption', 28), ('transcript', 29)]], {})}, verbose_name='intro')),
                ('default_section', models.CharField(choices=[('women', "Women's cancer"), ('children', 'Childhood cancer'), ('both', 'Both')], default='both', help_text='Pre-selects the section filter; visitors can change it.', max_length=16, verbose_name='default section filter')),
                ('last_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='medically reviewed by')),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when the page is shared in Telegram/Facebook. Generated automatically if empty.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.portalimage', verbose_name='social sharing image')),
            ],
            options={
                'verbose_name': 'directory page (where to go)',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name_uz', models.CharField(max_length=200, verbose_name='name (uz)')),
                ('name_ru', models.CharField(max_length=200, verbose_name='name (ru)')),
                ('kind', models.CharField(choices=[('svp', 'Family doctor point (SVP)'), ('polyclinic', 'District polyclinic'), ('onco_room', 'Onco-alertness room'), ('mother_child_centre', 'Mother & Child Health Centre / branch'), ('oncology_centre', 'Oncology centre (RONC / regional)'), ('paediatric_oncohaematology', 'Paediatric onco-haematology'), ('psych_support', 'Psychological support'), ('ngo', 'NGO / support group')], db_index=True, max_length=32, verbose_name='kind')),
                ('district_uz', models.CharField(blank=True, max_length=120, verbose_name='district (uz)')),
                ('district_ru', models.CharField(blank=True, max_length=120, verbose_name='district (ru)')),
                ('address_uz', models.CharField(blank=True, max_length=300, verbose_name='address (uz)')),
                ('address_ru', models.CharField(blank=True, max_length=300, verbose_name='address (ru)')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='phone')),
                ('hours_uz', models.CharField(blank=True, max_length=200, verbose_name='opening hours (uz)')),
                ('hours_ru', models.CharField(blank=True, max_length=200, verbose_name='opening hours (ru)')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='latitude')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))], verbose_name='longitude')),
                ('free_under_state_programme', models.BooleanField(db_index=True, default=False, verbose_name='free under the state programme')),
                ('sections', models.CharField(choices=[('women', "Women's cancer"), ('children', 'Childhood cancer'), ('both', 'Both')], db_index=True, default='both', max_length=16, verbose_name='sections')),
                ('verified_at', models.DateField(blank=True, null=True, verbose_name='data verified on')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='published')),
                ('external_id', models.CharField(blank=True, help_text='Identifier in an external registry (e.g. DMED) for future synchronisation.', max_length=64, verbose_name='external id')),
                ('external_source', models.CharField(blank=True, max_length=32, verbose_name='external source')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='directory.region', verbose_name='region')),
                ('services', models.ManyToManyField(blank=True, related_name='institutions', to='directory.service', verbose_name='services')),
            ],
            options={
                'verbose_name': 'institution',
                'verbose_name_plural': 'institutions',
                'ordering': ['region__sort_order', 'name_uz'],
                'indexes': [models.Index(fields=['region', 'kind', 'is_published'], name='directory_i_region__9722e9_idx')],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
