# Generated by Django 5.2.17 on 2026-09-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_regions_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorypage',
            name='og_image_generated',
            field=models.ImageField(blank=True, editable=False, help_text='Rendered automatically on publish when no sharing image is chosen.', upload_to='og/', verbose_name='generated sharing image'),
        ),
    ]
