# Generated by Django 5.2.17 on 2026-09-17 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_story_image_and_privacy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorypage',
            name='last_reviewed_at',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='reviewed on'),
        ),
        migrations.AlterField(
            model_name='directorypage',
            name='last_reviewed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='medically reviewed by'),
        ),
        migrations.AlterField(
            model_name='directorypage',
            name='medically_verified',
            field=models.BooleanField(default=False, editable=False, help_text="Shows the 'Verified by a doctor' badge. Set by the medical review workflow.", verbose_name='medically verified'),
        ),
    ]
