# Generated by Django 5.2.17 on 2026-09-15 06:58

import django.db.models.deletion
import uuid
import wagtail.fields
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('term', models.CharField(db_index=True, max_length=120, verbose_name='term')),
                ('definition', wagtail.fields.RichTextField(verbose_name='definition')),
                ('section', models.CharField(choices=[('women', "Women's cancer"), ('children', 'Childhood cancer'), ('both', 'Both sections')], default='both', max_length=16, verbose_name='section')),
                ('synonyms', models.CharField(blank=True, help_text='Comma-separated alternative spellings (e.g. Cyrillic, abbreviations).', max_length=300, verbose_name='synonyms')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'glossary term',
                'verbose_name_plural': 'glossary terms',
                'ordering': ['term'],
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
