# Generated by Django 5.2.17 on 2026-09-15 06:58

import apps.media_library.models
import django.db.models.deletion
import wagtail.fields
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('kind', models.CharField(choices=[('long', 'Long video (doctor interview, lecture)'), ('short_vertical', 'Short vertical video (mobilograph, social media)')], default='long', max_length=16, verbose_name='kind')),
                ('source', models.CharField(choices=[('upload', 'Uploaded file'), ('youtube', 'YouTube'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('tiktok', 'TikTok')], default='upload', max_length=16, verbose_name='source')),
                ('file', models.FileField(blank=True, help_text='Original upload. Never served directly — transcoded renditions are.', upload_to=apps.media_library.models.video_upload_path, verbose_name='video file')),
                ('external_url', models.URLField(blank=True, verbose_name='external URL')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration (seconds)')),
                ('doctor_name', models.CharField(blank=True, max_length=200, verbose_name="doctor's name")),
                ('doctor_org', models.CharField(blank=True, max_length=200, verbose_name="doctor's organisation")),
                ('transcript', wagtail.fields.RichTextField(blank=True, verbose_name='transcript')),
                ('subtitles_uz', models.FileField(blank=True, upload_to=apps.media_library.models.subtitle_upload_path, verbose_name='subtitles (uz, VTT)')),
                ('subtitles_ru', models.FileField(blank=True, upload_to=apps.media_library.models.subtitle_upload_path, verbose_name='subtitles (ru, VTT)')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=16, verbose_name='status')),
                ('renditions', models.JSONField(blank=True, default=dict, verbose_name='renditions')),
                ('processing_error', models.TextField(blank=True, verbose_name='processing error')),
                ('poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.portalimage', verbose_name='poster image')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'ordering': ['-created_at'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
