# Generated by Django 5.2.17 on 2026-09-17 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0005_alter_materialspage_last_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portaldocument',
            options={'permissions': [('choose_portaldocument', 'Can choose document')], 'verbose_name': 'document', 'verbose_name_plural': 'documents'},
        ),
        migrations.AlterModelOptions(
            name='portalimage',
            options={'permissions': [('choose_portalimage', 'Can choose image')], 'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
    ]
