# Generated by Django 5.2.17 on 2026-10-06 11:17

import apps.articles.illustrations
import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0007_alter_materialspage_intro'),
        ('wagtailcore', '0094_alter_page_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='topic',
            field=models.CharField(blank=True, choices=[('breast', 'Breast cancer'), ('cervical', 'Cervical cancer'), ('children', 'Childhood cancer')], db_index=True, help_text='Filter on the «Videos» page; empty = shown under «All» only.', max_length=16, verbose_name='topic'),
        ),
        migrations.CreateModel(
            name='VideoIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_image_generated', models.ImageField(blank=True, editable=False, help_text='Rendered automatically on publish when no sharing image is chosen.', upload_to='og/', verbose_name='generated sharing image')),
                ('story_image_generated', models.ImageField(blank=True, editable=False, help_text='Vertical image for Instagram/TikTok stories, rendered on publish.', upload_to='story/', verbose_name='generated story image (1080×1920)')),
                ('noindex', models.BooleanField(default=False, help_text='Adds a noindex meta tag. Use for drafts-in-public and utility pages.', verbose_name='hide from search engines')),
                ('last_reviewed_at', models.DateField(blank=True, editable=False, null=True, verbose_name='reviewed on')),
                ('medically_verified', models.BooleanField(default=False, editable=False, help_text="Shows the 'Verified by a doctor' badge. Set by the medical review workflow.", verbose_name='medically verified')),
                ('intro', wagtail.fields.StreamField([('rich_text', 0), ('callout', 4), ('cards_grid', 16), ('stat', 21), ('cta', 26), ('video', 31)], blank=True, block_lookup={0: ('apps.articles.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link', 'document-link', 'image', 'embed']}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger — do not delay'), ('success', 'Success / good news'), ('reassurance', 'Reassurance (this sign is not always cancer)'), ('alert', 'Alert strip with “!” (do not panic, do not delay)')], 'label': 'Kind'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 120, 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link'], 'label': 'Text'}), 4: ('wagtail.blocks.StructBlock', [[('kind', 1), ('title', 2), ('text', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Heading', 'max_length': 160, 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('cards', 'Cards'), ('icon_tiles', 'Icon tiles (risk factors)')], 'label': 'Layout'}), 7: ('wagtail.images.blocks.ImageBlock', [], {'label': 'Image'}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': apps.articles.illustrations.icon_choices, 'help_text': 'Designer icon shown on the pink tile (used when no image is uploaded).', 'label': 'Icon', 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 160}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link'], 'label': 'Text', 'required': False}), 11: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page', 'required': False}), 12: ('wagtail.blocks.URLBlock', (), {'label': 'External URL', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('page', 11), ('url', 12)]], {'label': 'Link', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('image', 7), ('icon', 8), ('title', 9), ('text', 10), ('link', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {'label': 'Cards', 'min_num': 1}), 16: ('wagtail.blocks.StructBlock', [[('title', 5), ('layout', 6), ('cards', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': "E.g. '1 из 8' or '45–65'.", 'label': 'Value', 'max_length': 40}), 18: ('wagtail.blocks.CharBlock', (), {'label': 'Label', 'max_length': 200}), 19: ('wagtail.blocks.CharBlock', (), {'label': 'Source', 'max_length': 200, 'required': False}), 20: ('wagtail.blocks.IntegerBlock', (), {'label': 'Year', 'max_value': 2100, 'min_value': 1990, 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('value', 17), ('label', 18), ('source', 19), ('year', 20)]], {}), 22: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Text', 'required': False}), 23: ('wagtail.blocks.CharBlock', (), {'label': 'Button label', 'max_length': 80}), 24: ('wagtail.blocks.StructBlock', [[('page', 11), ('url', 12)]], {'label': 'Link'}), 25: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary (section colour)'), ('secondary', 'Secondary')], 'label': 'Style'}), 26: ('wagtail.blocks.StructBlock', [[('text', 22), ('button_label', 23), ('link', 24), ('style', 25)]], {}), 27: ('wagtail.snippets.blocks.SnippetChooserBlock', ('media_library.Video',), {'label': 'Video from library', 'required': False}), 28: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube, Telegram, Instagram or TikTok link (used when no library video).', 'label': 'External URL', 'required': False}), 29: ('wagtail.blocks.CharBlock', (), {'label': 'Caption', 'max_length': 300, 'required': False}), 30: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link'], 'label': 'Transcript', 'required': False}), 31: ('wagtail.blocks.StructBlock', [[('video', 27), ('external_url', 28), ('caption', 29), ('transcript', 30)]], {})}, verbose_name='intro')),
                ('last_reviewed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='medically reviewed by')),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when the page is shared in Telegram/Facebook. Generated automatically if empty.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.portalimage', verbose_name='social sharing image')),
            ],
            options={
                'verbose_name': 'videos list',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
    ]
