# Generated by Django 5.2.17 on 2026-10-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0009_alter_materialspage_intro_alter_videoindexpage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoindexpage',
            name='eyebrow',
            field=models.CharField(blank=True, help_text="Small line above the title (empty = the design's wording).", max_length=80, verbose_name='eyebrow'),
        ),
        migrations.AddField(
            model_name='videoindexpage',
            name='lead',
            field=models.CharField(blank=True, max_length=300, verbose_name='short description'),
        ),
    ]
