# Generated by Django 5.2.17 on 2026-09-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_og_image_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionindexpage',
            name='story_image_generated',
            field=models.ImageField(blank=True, editable=False, help_text='Vertical image for Instagram/TikTok stories, rendered on publish.', upload_to='story/', verbose_name='generated story image (1080×1920)'),
        ),
        migrations.AddField(
            model_name='topicindexpage',
            name='story_image_generated',
            field=models.ImageField(blank=True, editable=False, help_text='Vertical image for Instagram/TikTok stories, rendered on publish.', upload_to='story/', verbose_name='generated story image (1080×1920)'),
        ),
    ]
