# Generated by Django 5.2.17 on 2026-09-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_alter_sectionindexpage_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionindexpage',
            name='open_first_topic',
            field=models.BooleanField(default=False, help_text='The design has no section overview: visitors go straight to the first menu topic (302). The overview stays visible in preview.', verbose_name='open the first topic'),
        ),
        migrations.AddField(
            model_name='topicindexpage',
            name='is_variant_group',
            field=models.BooleanField(default=False, help_text='E.g. breast / cervical cancer: the topic opens its first child page (302) and every child shows a switch between the variants (Figma design).', verbose_name='children are variants of one topic'),
        ),
    ]
